### ISSUE TITLE
[feature]: confirm password input on signup page

### ISSUE THREAD

**Issue by ejcheng** [polygon-isecure/front#5]
If `confirmPassword` box does not match password box, show red error highlighting.

**Comment by mikayelgr** [comment]
Good feature request 👍 

The only thing that I worry about is the sign up form taking too much space on the screen. Also, I am not sure whether the password confirmation field should be validated by the core also. I think frontend validation is enough.

Are you open to creating a PR?

**Comment by ejcheng** [comment]
> Good feature request 👍
> 
> The only thing that I worry about is the sign up form taking too much space on the screen. Also, I am not sure whether the password confirmation field should be validated by the core also. I think frontend validation is enough.
> 
> Are you open to creating a PR?

With the way the current signup form is structured, I'm not sure on how to implement the confirm password field, I was hoping you or another possible contributor could do it.

**Comment by mikayelgr** [comment]
Sure, I will have a look at other projects to see how they create their registration forms and will update the UI if I find a nice one.

**Comment by mikayelgr** [comment]
I found some designs on [Dribbble](https://dribbble.com/):

- https://dribbble.com/shots/13907242
- https://dribbble.com/shots/17295056-Forms
- https://dribbble.com/shots/17411928-Account-Creation
- https://dribbble.com/shots/17425419-DailyUI01-Sign-Up
- https://dribbble.com/shots/15004408-Stages-Website-Sign-Up

and this one on [Behance](https://behance.net/):

- https://www.behance.net/gallery/127006201/Plant-App-Sign-up-login-UI?tracking_source=search_projects%7Csign%20up

Implementing a password strength bar is also a great idea I think. I will need to find a way to create one with Chakra UI. 

Feedback is needed for both of these changes to the UI is required though. I will ask the community on Discord which design they like the most.

**Comment by ejcheng** [comment]
> * behance.net/gallery/127006201/Plant-App-Sign-up-login-UI?tracking_source=search_projects%7Csign%20up

https://pro.chakra-ui.com/components/application/authentication

What about the "Login with centred form" on this page? It comes with source code.

**Comment by mikayelgr** [comment]
> > * behance.net/gallery/127006201/Plant-App-Sign-up-login-UI?tracking_source=search_projects%7Csign%20up
> 
> https://pro.chakra-ui.com/components/application/authentication
> 
> What about the "Login with centred form" on this page? It comes with source code.

We could use some parts from the website for the login screen (like remember me checkbox), but I am not going to change the rest of the layout, since pages related to authentication are the children of a custom [`<AuthUi />`](https://github.com/polygon-isecure/ui/blob/nightly/src/modules/auth/AuthUi.tsx) component that takes care of responsiveness and placement of the helper links. 

For now, the login screen is fine and the sign-up screen is my main focus in this issue.

**Comment by ejcheng** [comment]
> pro.chakra-ui.com/components/application/authentication

What about this? https://chakra-templates.dev/templates/forms/authentication/simpleSignupCard

My bad, I forgot we were focusing on only the signup page.

**Comment by mikayelgr** [comment]
Looks fine, though our form includes more fields than in the template above.

Here are all the fields that our signup form needs to process:

- `firstName`
- `lastName`
- `username`
- `email`
- `password`
- `repeatPassword` - new

and possibly a hidden `csrfToken` field to protect against CSRF attacks.

**Comment by ejcheng** [comment]
> Looks fine, though our form includes more fields than in the template above.
> 
> Here are all the fields that our signup form needs to process:
> 
> * `firstName`
> * `lastName`
> * `username`
> * `email`
> * `password`
> * `repeatPassword` - new
> 
> and possibly a hidden `csrfToken` field to protect against CSRF attacks.

I can add those extra fields to the front-end, but I am not very experienced in back-end work. Would you be able to hook that form up to the core backend?

**Comment by mikayelgr** [comment]
Sure, I will make the backend to handle the CSRF token logic.

**Comment by mikayelgr** [comment]
Also, while adding the fields could you please also add some padding to the `children` of `<AuthUi />`? It looks a bit weird on mobile.

![iOS screenshot](https://user-images.githubusercontent.com/56165400/157258395-a966dab0-2819-4ec5-ab8f-bd73d07f533c.jpeg)

**Comment by ejcheng** [comment]
> Also, while adding the fields could you please also add some padding to the `children` of `<AuthUi />`? It looks a bit weird on mobile.
> 
> ![iOS screenshot](https://user-images.githubusercontent.com/56165400/157258395-a966dab0-2819-4ec5-ab8f-bd73d07f533c.jpeg)

Okay, I will add the padding.

**Comment by mikayelgr** [comment]
Thank you.

**Comment by ejcheng** [comment]
> Thank you.

I'm extremely confused on how the AuthUi is structured, where am I supposed to add the padding? Should I just directly add it to the signup.tsx?

**Comment by mikayelgr** [comment]
> > Thank you.
> 
> I'm extremely confused on how the AuthUi is structured, where am I supposed to add the padding? Should I just directly add it to the signup.tsx?

I should consider updating the documentation for that component... You can add the padding on this line: https://github.com/polygon-isecure/ui/blob/nightly/src/modules/auth/AuthUi.tsx#L93

**Comment by ejcheng** [comment]
> > > Thank you.
> 
> > 
> 
> > I'm extremely confused on how the AuthUi is structured, where am I supposed to add the padding? Should I just directly add it to the signup.tsx?
> 
> 
> 
> I should consider updating the documentation for that component... You can add the padding on this line: https://github.com/polygon-isecure/ui/blob/nightly/src/modules/auth/AuthUi.tsx#L93

I see, I'll update it there in a couple hours.
