### ISSUE TITLE
docs: Update the documentation

### ISSUE THREAD

**Issue by mikayelgr** [polygon-isecure/front#6]
This is a tracking issue for updating the documentation of Polygon's UI.

**Comment by ejcheng** [comment]
@michaelgrigoryan25 Can you also assign this to me? I can help with this, thanks

**Comment by mikayelgr** [comment]
> @michaelgrigoryan25 Can you also assign this to me? I can help with this, thanks

Sure! 

Thank you!

**Comment by ejcheng** [comment]
> > @michaelgrigoryan25 Can you also assign this to me? I can help with this, thanks
> 
> Sure!
> 
> Thank you!

No problem!

Of course, some of the technologies used in the stack are ones I'm not too experienced in, so I wouldn't be able to write good docs for them.

**Comment by mikayelgr** [comment]
@import-brain will you be able to make a PR for this?

**Comment by ejcheng** [comment]
> @import-brain will you be able to make a PR for this?

What do you want me to do in the documentation for the PR?

**Comment by mikayelgr** [comment]
Could you please include the whole configuration and hosting process? (e.g. environment variables) 

Both for local setup and on a remote one (like Vercel).

**Comment by ejcheng** [comment]
> Could you please include the whole configuration and hosting process? (e.g. environment variables)
> 
> Both for local setup and on a remote one (like Vercel).

I know I should have asked this earlier, but what is ```IRON_SESSION_SECRET```? I understand what ```POLYGON_CORE_URL``` is, but not the other one. Other than that, I can get working on writing docs for the UI.

**Comment by ejcheng** [comment]
Just made something that will work temporarily, but will need to be expanded on much more in the future. Please look at PR #10

**Comment by mikayelgr** [comment]
Thanks for the help @import-brain! Closed with #10
